ex3:
	../wolves-squirrels.out ex3.in 3 4 4 4 > ex3.out

world10-1:
	../wolves-squirrels.out world_10.in 20 5 30 5 > world10-1.out

world10-2:
	../wolves-squirrels.out world_10.in 20 50 30 1000000 > world10-2.out

world100:
	../wolves-squirrels.out world_100.in 20 50 30 100000 > world100.out

world1000:
	../wolves-squirrels.out world_1000.in 20 50 30 10000 > world1000.out
